"""
IPT CitySpace – Scientific Parameters (VERSÃO FINAL ESTÁVEL)
"""

# GRID
GRID_ROWS = 8
GRID_COLS = 16
GRID_NAME = f"{GRID_ROWS}x{GRID_COLS}"

CENTER_URBAN_ON_GRID = True

# SCALE XY
REAL_EXTENT_X_METERS = 500.0
CELL_SIZE_PHYSICAL_METERS = 0.01
ZOOM_LEVEL = 1.0

BASE_CELL_SIZE_METERS = REAL_EXTENT_X_METERS / GRID_COLS

def get_cell_size_meters():
    return BASE_CELL_SIZE_METERS * ZOOM_LEVEL

def get_scale_xy():
    return REAL_EXTENT_X_METERS / (GRID_COLS * CELL_SIZE_PHYSICAL_METERS * ZOOM_LEVEL)

# Z (PIN)
PIN_MIN_CM = 0.0
PIN_MAX_CM = 10.0

MAX_HEIGHT_METERS = 40.0
METERS_TO_CM = PIN_MAX_CM / MAX_HEIGHT_METERS

def meters_to_pin_cm(z_m):
    return z_m * METERS_TO_CM

# HEIGHT MODEL
HEIGHT_PERCENTILE_BUILDING = 95
HEIGHT_PERCENTILE_TERRAIN = 10
MIN_BUILDING_FOOTPRINT_RATIO = 0.15

# RUNNER
FRAME_RATE = 10
SCANNER_SPEED = 1.0

# DEBUG
print("\n[CONFIG OK]")
print(f"GRID: {GRID_NAME}")
print(f"CELL: {BASE_CELL_SIZE_METERS:.2f} m")
print(f"SCALE: 1:{int(get_scale_xy())}")
print(f"PIN: {PIN_MIN_CM}-{PIN_MAX_CM} cm")
print(f"Z: 1cm = {MAX_HEIGHT_METERS / PIN_MAX_CM:.2f} m\n")
